version: '3.8'
 
services:
  jenkins:
    image: jenkins:latest
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
  sonarcube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      SONARQUBE_DATABASE_URL: jdbc:postgresql://postgres:5432/sonar
 
volumes:
  jenkins-data:
