version: '3.7'
 
services:

  jenkins:

    image: jenkins/jenkins:lts

    container_name: jenkins

    restart: always

    ports:

      - "8080:8080"

    volumes:

      - "./jenkins_home:/var/jenkins_home"

    networks:

      - jenkins-net
 
  sonarqube:

    image: sonarqube:latest

    container_name: sonarqube

    restart: always

    ports:

      - "9000:9000"

    networks:

      - jenkins-net
 
networks:

  jenkins-net:
