version: "3.8"  # Adjust if necessary based on your Docker version
 
services:

  jenkins:

    image: jenkins/jenkins:lts  # Use LTS version for stability

    ports:

      - "8080:8080"  # Map container port 8080 to host port 8080 for Jenkins web interface

    volumes:

      - jenkins-data:/var/jenkins_home  # Persist Jenkins data

    environment:

      - DISALLOW_ANONYMOUS_LOGIN=yes  # Optional: Disable anonymous login for security
 
  sonarqube:

    image: sonarqube:latest  # Use latest version for testing purposes (consider LTS for production)

    ports:

      - "9000:9000"  # Map container port 9000 to host port 9000 for SonarQube web interface

    volumes:

      - sonarqube-data:/var/sonarqube/data  # Persist SonarQube data
 
volumes:

  jenkins-data:  # Named volume for Jenkins data persistence

  sonarqube-data:  # Named volume for SonarQube data persistence
